-- Create activity_logs table
CREATE TABLE IF NOT EXISTS activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL CHECK (type IN ('STAKE', 'ATTEST', 'REVOKE')),
    wallet TEXT REFERENCES users(wallet) NOT NULL,
    target TEXT NOT NULL, -- The target wallet or project name
    amount TEXT, -- Optional: "10 ETH" or "5 Trust"
    metadata JSONB DEFAULT '{}'::jsonb, -- Store extra IDs (project_id, score, etc)
    tx_hash TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for fast feed queries
CREATE INDEX IF NOT EXISTS idx_activity_logs_created_at ON activity_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_logs_wallet ON activity_logs(wallet);

-- Enable RLS
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;

-- Policy: Public read
CREATE POLICY "Activity logs are public" 
ON activity_logs FOR SELECT 
USING (true);

-- Policy: Auth insert (for API usage)
CREATE POLICY "Authenticated users can insert activity" 
ON activity_logs FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');
