-- Create stakes table
CREATE TABLE IF NOT EXISTS stakes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES projects(project_id) NOT NULL,
    user_wallet TEXT REFERENCES users(wallet) NOT NULL,
    amount NUMERIC NOT NULL,
    tx_hash TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE stakes ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can read stakes (for activity feed)
CREATE POLICY "Public stakes are viewable by everyone" 
ON stakes FOR SELECT 
USING (true);

-- Policy: Users can insert stakes (via API/backend usually, but allowing auth users to be safe if strictly RLS)
-- Ideally, inserts happen via service role in API, but if we use client SDK:
CREATE POLICY "Users can insert their own stakes" 
ON stakes FOR INSERT 
WITH CHECK (auth.role() = 'authenticated'); -- Logic validation happens in API
